name: ci

on:
  workflow_dispatch:

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete 'mhddos_proxy' containers older than a week
        uses: snok/container-retention-policy@v1
        with:
          image-names: python-dev, js-dev
          cut-off: A week ago UTC
          account-type: personal
          keep-at-least: 1
          untagged-only: true
          token: ${{ GITHUB_TOKEN }}
